name: Build

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  checking:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Clean Build
        run: ./gradlew --stop
      - name: Run Build
        run: ./gradlew build --no-daemon