name: Build status

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  building:
    runs-on:  ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache
      - name: Cache (NDK)
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk/21.0.6113669
          key: ndk-cache
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.0.6113669'
      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper
      - name: Run Gradle build
        run: ./gradlew build --continue
      - name: Stop Gradle
        run: ./gradlew --stop